Repository jenkinsci/promoted-builds-plugin, pull requests merged in 2023-06, with the labels that each got.

#240 Remove unused divBasedFormLayout conditionals in jelly files
  src/main/resources/hudson/plugins/promoted_builds/PromotionProcess/process-config.jelly
  src/main/resources/hudson/plugins/promoted_builds/PublisherImpl/config.jelly
  src/main/resources/lib/promoted_builds/blockWrapper.jelly
Labels: chore

#241 Update hamcrest
  pom.xml
  src/test/java/hudson/plugins/promoted_builds/LastBuildPromotionStatusColumnTest.java
Labels: dependencies

#244 Modernize plugin for June 2023
  pom.xml
  src/main/java/hudson/plugins/promoted_builds/JobPropertyImpl.java
  src/main/java/hudson/plugins/promoted_builds/PromotedBuildAction.java
  src/main/java/hudson/plugins/promoted_builds/PromotedProjectAction.java
  src/main/java/hudson/plugins/promoted_builds/Promotion.java
  src/main/java/hudson/plugins/promoted_builds/PromotionCondition.java
  src/main/java/hudson/plugins/promoted_builds/PromotionPermissionHelper.java
  src/main/java/hudson/plugins/promoted_builds/PromotionProcess.java
  src/main/java/hudson/plugins/promoted_builds/PromotionTargetAction.java
  src/main/java/hudson/plugins/promoted_builds/Status.java
  src/main/java/hudson/plugins/promoted_builds/conditions/DownstreamPassCondition.java
  src/main/java/hudson/plugins/promoted_builds/conditions/GroovyCondition.java
  src/main/java/hudson/plugins/promoted_builds/conditions/ManualCondition.java
  src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/ConditionsContext.java
  src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/JobDslPromotionProcessConverter.java
  src/main/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsContext.java
  src/main/java/hudson/plugins/promoted_builds/parameters/PromotedBuildParameterDefinition.java
  src/main/java/hudson/plugins/promoted_builds/util/ItemPathResolver.java
  src/main/java/hudson/plugins/promoted_builds/util/JenkinsHelper.java
  src/test/java/hudson/plugins/promoted_builds/ConfigurationDoCheckTest.java
  src/test/java/hudson/plugins/promoted_builds/ConfigurationRoundtripTest.java
  src/test/java/hudson/plugins/promoted_builds/PromotedBuildActionTest.java
  src/test/java/hudson/plugins/promoted_builds/PromotedBuildRebuildParameterProviderTest.java
  src/test/java/hudson/plugins/promoted_builds/PromotionTest.java
  src/test/java/hudson/plugins/promoted_builds/RemoteApiTest.java
  src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionBug22005.java
  src/test/java/hudson/plugins/promoted_builds/conditions/ManualConditionTest.java
  src/test/java/hudson/plugins/promoted_builds/conditions/inheritance/ManualConditionInheritanceTest.java
  src/test/java/hudson/plugins/promoted_builds/integrations/jobdsl/PromotionsDslContextExtensionTest.java
  src/test/java/hudson/plugins/promoted_builds/util/ItemPathResolverTest.java
Labels: internal
